### ISSUE TITLE
Traducción enigma2 español

### ISSUE THREAD

**Issue by Jglez3** [iqas/e2gui#1]
Soy Joannnn de Linux-Box, el que ha traducido prácticamente todo.

En el archivo /po/es.po la primera línea hay que cambiarla, desde POedit no se puede y por eso la dejé tal cual.

Está comentada y pone:
``# German translations for Enigma2.``

Habría que poner:
``# Spanish translations for Enigma2.``

**Comment by villak** [comment]
Ok yo con Linux si puedo, ya me encargo.
Gracias

**Comment by villak** [comment]
Listo Joan ya esta actualizado en el git todo
Gracias!

**Comment by villak** [comment]
aqui tienes la captura del nuevo skin.
https://dl.dropboxusercontent.com/u/47361066/traducciones.jpg

**Comment by Jglez3** [comment]
Hay un pequeño error en mi nick en el equipo de traducción, le falta una 'n' más, son 4. ``Joannnn``

Y la zona donde pone ``Traducido por: Joan González, joan@gonzalezcrego.es`` puedes quitar mi e-mail y sustituirlo por la web de Linux-Box o simplemente dejar solo mi nombre, seguramente se puso automáticamente al estar traduciendo con Poedit.

Gracias!

**Comment by villak** [comment]
Ok sin problemas. Quieres que ponga tu Twitter o Facebook¿ La web Linux box
ya está más arriba. Si es así Dame tu dirección.

**Comment by Jglez3** [comment]
Mi twitter está de adorno y Facebook no tengo, así que... de momento déjalo tal cual, mientras no llegue spam estaremos tranquilos.

Cambia lo del nick y ya está.

**Comment by villak** [comment]
De acuerdo, aunque spam tampoco creo que llegue mucho pues solo se refleja
en el nuevo skin que estoy preparando el metrixhd original portado a
openplus. Por cierto si puedes y quieres, en unos dias te lo paso y lo
testeas.

El 2 de junio de 2015, 11:50, Joan González <notifications@github.com>
escribió:

> Mi twitter está de adorno y Facebook no tengo, así que... de momento
> déjalo tal cual, mientras no llegue spam estaremos tranquilos.
>
> Cambia lo del nick y ya está.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iqas/e2gui/issues/1#issuecomment-107899651>.
>



-- 
*ViptronicK *http://www.viptronick.com/
Propiedad: José M. Villatoro Hidalgo.
Telf. 699128919

*La información contenida en este correo electrónico es confidencial,
pudiendo revestir el carácter de reservada. Está dirigida exclusivamente a
la persona o personas indicadas como destinatarios. No está autorizado y
puede llegar a ser ilegal, el acceso o cualquier otro uso que se haga de
dicha información por cualquier persona que no sea destinataria de la
misma. Si este mensaje le ha llegado por error y usted no es la persona
destinataria, deberá proceder a borrarlo, sin hacer ningún uso del mismo ni
retransmitirlo a terceros. El no cumplimiento de la presente cláusula podrá
desencadenar las correspondientes acciones legales. Queda a su elección la
posibilidad de avisar el remitente sobre el destino erróneo al que ha sido
enviado el mensaje.*
*P *Antes de imprimir este e-mail piense bien si es necesario hacerlo. El
medioambiente es cosa de todos.

**Comment by Jglez3** [comment]
Si, claro. Pásamelo cuando lo tengas y lo pruebo, así si hay cualquier fallo entre los dos lo vemos antes seguro.

Aunque ahora que me he acostumbrado al openplusHD... cuando voy al otro deco que lo tengo con MetrixHD me parece hasta raro.

**Comment by villak** [comment]
Hombre a mi tambien me gusta mas, es solo para que puedan escoger, no a
todos nos gusta lo mismo, eso si te digo para mi gusto esta mejor que el de
ATV, tipo de letras mas pulidas....
Gracias

El 2 de junio de 2015, 12:07, Joan González <notifications@github.com>
escribió:

> Si, claro. Pásamelo cuando lo tengas y lo pruebo, así si hay cualquier
> fallo entre los dos lo vemos antes seguro.
>
> Aunque ahora que me he acostumbrado al openplusHD... cuando voy al otro
> deco que lo tengo con MetrixHD me parece hasta raro.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iqas/e2gui/issues/1#issuecomment-107905893>.
>



-- 
*ViptronicK *http://www.viptronick.com/
Propiedad: José M. Villatoro Hidalgo.
Telf. 699128919

*La información contenida en este correo electrónico es confidencial,
pudiendo revestir el carácter de reservada. Está dirigida exclusivamente a
la persona o personas indicadas como destinatarios. No está autorizado y
puede llegar a ser ilegal, el acceso o cualquier otro uso que se haga de
dicha información por cualquier persona que no sea destinataria de la
misma. Si este mensaje le ha llegado por error y usted no es la persona
destinataria, deberá proceder a borrarlo, sin hacer ningún uso del mismo ni
retransmitirlo a terceros. El no cumplimiento de la presente cláusula podrá
desencadenar las correspondientes acciones legales. Queda a su elección la
posibilidad de avisar el remitente sobre el destino erróneo al que ha sido
enviado el mensaje.*
*P *Antes de imprimir este e-mail piense bien si es necesario hacerlo. El
medioambiente es cosa de todos.
